title: Kartiks Mega site
author: Kartik Kumar
email: k.kumar4354@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is my blog
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Kartik Kumar
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  404Kartik
    linkedIn: in/kartikkum

 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
